"""
generator/anchors_spec.py -- declarative anchor specs, resolved against
data/<slug>/normalised-events.json by scripts/find_anchors.py.

  role   : first_symptom | onset | decisive | contradiction | ticket | context
  match  : source (exact, optional), re (regex on description, required),
           rule_id (optional), ts_from / ts_to (HH:MM:SS UTC, optional),
           pick: first | last | all
  expect : 'rule_hit' | 'context'   (asserted by find_anchors.py)
  check  : True => part of the scenario's "cheapest decisive check" evidence set
"""


def _a(key, role, label, expect, re, source=None, rule_id=None, ts_from=None, ts_to=None, pick="first", check=False):
    return {"key": key, "role": role, "label": label, "expect": expect, "check": check,
            "match": {"source": source, "re": re, "rule_id": rule_id, "ts_from": ts_from, "ts_to": ts_to, "pick": pick}}


ANCHORS = {
    "s1": [
        _a("first_symptom", "first_symptom", "Buried P4: heap > 70% on hip-esb-odes-large pods (Splunk SPL-HEAP001)", "rule_hit",
           r"heap > 70%", source="Splunk", rule_id="SPL-HEAP001", check=True),
        _a("lag_onset", "onset", "First Kafka lag sample on the large group, rising (06:00, below rule threshold)", "context",
           r"opsfin-01-neo-odes-large [\d,]+ \(rising\)", source="Kafka", ts_from="05:55:00", ts_to="06:10:00"),
        _a("lag_rule_hit", "onset", "First Kafka lag rule hit: lag on large group, 0 on the 6 other groups", "rule_hit",
           r"lag 0 on 6 other processing groups", source="Kafka", rule_id="KFK-LAG-004", check=True),
        _a("stall_onset", "onset", "Computed: ASN_INT exchanges INPROGRESS at half-flow 2/4, none has exited half-flow 2", "context",
           r"INPROGRESS at halfflow 2/4", source="SONAR"),
        _a("oom_1", "onset", "OOMKilled, pod restart 1 (06:35)", "rule_hit", r"restart 1", source="Splunk", rule_id="SPL-OOM001"),
        _a("oom_2", "onset", "OOMKilled, pod restart 2 (06:52)", "rule_hit", r"restart 2", source="Splunk", rule_id="SPL-OOM001"),
        _a("lag_alert", "onset", "HIPMON Consumer Lag alert LAG01 (07:05)", "rule_hit", r"Consumer lag", source="HIPMON",
           rule_id="HIPMON-LAG01"),
        _a("hlth_45k", "onset", "Hourly critical report 07:30: InProgress=45,212", "rule_hit", r"InProgress=45,212", source="SONAR",
           rule_id="SNR-HRLY-CRIT"),
        _a("user_ticket", "ticket", "User incident: No ASN integrated in S4 - trucks waiting", "rule_hit", r"^INC10790101",
           source="ServiceNow"),
        _a("contra_inflow", "contradiction", "Contradiction: ASN inflow LOWER than last Thursday", "context",
           r"ASN_INT inflow in last 5 min", source="SONAR", ts_from="07:25:00", ts_to="07:35:00", check=True),
        _a("contra_other_groups", "contradiction", "Contradiction: lag 0 on all 6 other processing groups (07:30)", "rule_hit",
           r"lag 0 on 6 other processing groups", source="Kafka", ts_from="07:25:00", ts_to="07:35:00", check=True),
        _a("decisive_payload", "decisive", "Avg ASN payload ~3x baseline (KB), 06:30", "context",
           r"ASN_INT avg payload", source="SONAR", ts_from="06:25:00", ts_to="06:35:00", check=True),
        _a("decisive_heap", "decisive", "Heap ~90%+ on odes-large pods with GC pause up, 06:30", "context",
           r"heap_pct .* on hip-esb-odes-large", source="Splunk", ts_from="06:25:00", ts_to="06:35:00", check=True),
        _a("baseline_heap", "context", "Baseline heap (flat, 04:20) before the linear climb", "context",
           r"heap_pct .* on hip-esb-odes-large", source="Splunk", ts_from="04:15:00", ts_to="04:25:00"),
        _a("sto_batch", "context", "Trigger: STO batch of 3,850 STOs released", "context", r"STO batch released", source="SONAR"),
    ],
    "s2": [
        _a("first_symptom", "first_symptom", "Last IDoc exchange from PI7 hub CE created 13:29:48", "context",
           r"last EMEA_SAPCE_PI7_IDOC_DELVRY07_TO_MANH exchange created at 13:29:48", source="SONAR"),
        _a("heartbeat_last", "onset", "Last listener heartbeat 13:30:12", "context", r"LAST heartbeat received", source="SONAR"),
        _a("heartbeat_absent", "decisive", "Computed: listener heartbeat absent for 5 min", "context",
           r"heartbeat absent for 5 min", source="SONAR", check=True),
        _a("silence_5m", "decisive", "Computed: no CE exchange created for 5 min", "context",
           r"exchange created for 5 min", source="SONAR", check=True),
        _a("zero_inbound", "decisive", "Inbound exchanges from PI7 hub CE in 5-min bucket: 0 (baseline 180) at 13:35", "context",
           r"hub CE in last 5 min: 0 \(baseline 180\)", source="SONAR", check=True),
        _a("baseline_inbound", "context", "Baseline: CE inbound ~174-186 per 5 min before 13:30", "context",
           r"hub CE in last 5 min: 1[78]\d \(baseline 180\)", source="SONAR", ts_from="13:25:00", ts_to="13:31:00"),
        _a("lag_zero", "decisive", "Kafka lag 0 on all 7 processing groups (13:45)", "context", r"lag 0 on all 7", source="Kafka",
           ts_from="13:44:00", ts_to="13:46:00", check=True),
        _a("nodata_alert", "onset", "HIPMON: NO DATA FROM SAPCE/Pi7 IN LAST 60 minutes (14:10)", "rule_hit",
           r"NO DATA FROM SAPCE/Pi7", source="HIPMON", rule_id="HIPMON-NODATA01"),
        _a("contra_health", "contradiction", "Contradiction: listener health check green (UP), heap 42% CPU 11% after 13:30:12", "context",
           r"actuator/health -> 200 UP", source="Splunk", ts_from="13:31:00", ts_to="14:00:00", check=True),
        _a("contra_heap_flat", "contradiction", "Contradiction: listener JVM heap flat at baseline after 13:30", "context",
           r"heap_pct .* hip-pi7-idoc-listener", source="Splunk", ts_from="13:40:00", ts_to="13:41:00", pick="all"),
        _a("replay_no_effect", "context", "L1 YODI replay: 0 exchanges matched, nothing to replay", "context",
           r"0 exchanges matched", source="SONAR"),
        _a("user_ticket", "ticket", "User incident: CZ warehouse - no deliveries from SAP", "rule_hit", r"^INC10790202",
           source="ServiceNow"),
        _a("crit_raised", "ticket", "Priority raised to Critical (15:49)", "context",
           r"INC10790202 priority changed to '1 - Critical'", source="ServiceNow"),
        _a("other_hubs_ok", "contradiction", "Other PI7 hubs (UK/IT/NE) still flowing at baseline", "context",
           r"hub UK in last 5 min: 1\d\d", source="SONAR", ts_from="13:40:00", ts_to="13:50:00", check=True),
    ],
    "s3": [
        _a("first_symptom", "first_symptom", "First Workato job failure: Recipe function call failed (09:52:03)", "rule_hit",
           r"Recipe function call failed", source="Workato", rule_id="WKT-JOBFAIL-001"),
        _a("vendor_notice", "decisive", "Vendor release notice 09:40, no HIP change record (smoking gun)", "context",
           r"Vendor Notice.*Workato platform release", source="Change", check=True),
        _a("hipmon_first", "onset", "First HIPMON: Failed to fetch ConfigForDocSending on SAPCE YLCD01 (09:55)", "rule_hit",
           r"SAPCE_YLCD01.*ConfigForDocSending", source="HIPMON", rule_id="HIPMON-DEFAULT"),
        _a("hipmon_sapne", "onset", "HIPMON reaches SAPNE (10:01)", "rule_hit", r"SAPNE_YLCD01.*ConfigForDocSending", source="HIPMON"),
        _a("failed_group", "decisive", "Computed: 30+ IDoc-out exchanges FAILED, identical reason, all hubs/types (10:05)", "context",
           r"identical event.reason 'SAP RFC Error: Failed to fetch ConfigForDocSending'", source="SONAR",
           ts_from="10:04:00", ts_to="10:06:00", check=True),
        _a("contra_partial", "contradiction", "Contradiction: YHIPDELVRY07 to SAPNE still succeeding intermittently", "context",
           r"still succeeding intermittently", source="SONAR", ts_from="10:06:00", ts_to="10:08:00", check=True),
        _a("contra_complete_line", "contradiction", "A YHIPDELVRY07 -> SAPNE exchange COMPLETE after failures began", "context",
           r"exchange COMPLETE after the failures began", source="SONAR"),
        _a("contra_gw_ok", "contradiction", "Contradiction: SAPNE RFC gateway health check OK", "context",
           r"SAPNE RFC gateway health check OK", source="Splunk", ts_from="10:05:00", ts_to="10:15:00", check=True),
        _a("user_ticket", "ticket", "User incident: Shipment completed in Manhattan but not integrated to SAP", "rule_hit",
           r"^INC10790303", source="ServiceNow"),
        _a("user_ticket_2", "ticket", "Second user incident, different warehouse", "rule_hit", r"^INC10790331", source="ServiceNow"),
        _a("hourly_failed", "onset", "Hourly critical report 10:00 shows Failed above threshold", "rule_hit", r"HLTH_CHK 10:00Z",
           source="SONAR", rule_id="SNR-HRLY-CRIT"),
    ],
    "s4": [
        _a("first_symptom", "first_symptom", "MFT: BPM_to_FM_0200.csv SUCCESS, 4.1 MB, declared 128,400 != actual 77,032 rows", "context",
           r"BPM_to_FM_0200.csv .*ROW COUNT MISMATCH", source="MFT", check=True),
        _a("patching_window", "context", "EMEA patching window opens 01:30 (routine, approved)", "context",
           r"EMEA monthly patching window", source="Change"),
        _a("adapter_down", "context", "SFG ESB adapter: 0 of 4 sessions active after reboot (01:41)", "context",
           r"0 of 4 sessions active", source="Splunk"),
        _a("export_ok", "contradiction", "Export log: ANAPLAN_BPM_EXPORT ended OK at 01:58, 128400 rows (source export was normal)",
           "context", r"ANAPLAN_BPM_EXPORT ended OK", source="Splunk", check=True),
        _a("hf1_entry", "decisive", "Sonar: half-flow 1 ENTRYINFO, halfflow.missing 2/4 (02:00:07)", "context",
           r"01_MFT ENTRYINFO status INPROGRESS", source="SONAR", check=True),
        _a("hf1_exit", "decisive", "Sonar: half-flow 1 EXITINFO, last event of the exchange (02:00:09)", "context",
           r"01_MFT EXITINFO status INPROGRESS", source="SONAR"),
        _a("missing_hf2", "decisive", "Computed: exchange INPROGRESS at 2/4, half-flow 2 has NO event, never FAILED", "context",
           r"expected half-flow GLBL_OPSF_ANAPLAN_BPM_to_FM_02_ESB has NO event", source="SONAR", check=True),
        _a("hourly_0300", "contradiction", "Hourly report 03:00: exchange listed under InProgress, Failed=0", "context",
           r"HLTH_CHK 03:00Z.*BPM_to_FM \(1", source="SONAR", check=True),
        _a("hourly_0700", "contradiction", "Hourly report 07:00: still under InProgress (oldest 4h59m), Failed=0", "context",
           r"HLTH_CHK 07:00Z.*BPM_to_FM \(1", source="SONAR"),
        _a("adapter_up", "context", "SFG ESB adapter sessions re-established 02:14", "context",
           r"4 of 4 sessions re-established", source="Splunk"),
        _a("db_lock", "onset", "Splunk DB lock rule SPL-DBLOCK001 (07:49)", "rule_hit", r"lock wait", source="Splunk",
           rule_id="SPL-DBLOCK001"),
        _a("hipmon_lock", "onset", "First HIPMON on FRCPD FKF generation: database lock (07:52)", "rule_hit", r"FRCPD",
           source="HIPMON"),
        _a("user_ticket", "ticket", "User incident: FRCPD database locked, FKF not generated", "rule_hit", r"^INC10790404",
           source="ServiceNow"),
        _a("normal_bpm_0400", "context", "Normal 04:00 BPM_to_FM run for comparison (6.8 MB, rows match)", "context",
           r"BPM_to_FM_0400.csv .*declared_rows=128,400 actual_rows=128,400", source="MFT"),
    ],
    "s5": [
        _a("first_symptom", "first_symptom", "Splunk: hip-fwk-transco-cache pod restart 1 (00:20:06), informational", "rule_hit",
           r"restarted \(restart 1\)", source="Splunk", rule_id="SPL-PODRST001", check=True),
        _a("first_error", "onset", "First Connection refused error on EMEA_SAPIT_SALESORDER_01_ESB_V2 (00:55:03)", "context",
           r"EMEA_SAPIT_SALESORDER_01_ESB_V2 FAILED", source="SONAR", check=True),
        _a("failed_group_0100", "decisive", "Computed: identical event.reason across 21+ half-flows in 4 projects (01:00)", "context",
           r"identical event.reason 'Connection refused: hip-fwk-transco-cache", source="SONAR",
           ts_from="01:00:00", ts_to="01:00:59"),
        _a("failed_group_0115", "decisive", "Computed: 134 failed exchanges across 30+ half-flows in 4 projects, same error (01:15)",
           "context", r"identical event.reason 'Connection refused: hip-fwk-transco-cache", source="SONAR",
           ts_from="01:15:00", ts_to="01:15:59", check=True),
        _a("hipmon_first", "onset", "First HIPMON alerts on transco flows (00:56+)", "rule_hit",
           r"Connection refused: hip-fwk-transco-cache", source="HIPMON"),
        _a("kafka_four", "onset", "Kafka lag rule on four groups at once", "rule_hit", r"sapit-01-default .*kepler-01-default",
           source="Kafka", rule_id="KFK-LAG-004"),
        _a("apigee_5xx", "onset", "Apigee 5xx across endpoints (01:08-01:18)", "rule_hit", r"Apigee 503", source="Apigee",
           rule_id="APG-5XX-012"),
        _a("six_incidents", "ticket", "Six auto incidents from six different rules (01:15-01:16), primary INC10790505", "rule_hit",
           r"^INC10790505", source="ServiceNow"),
        _a("contra_ready", "contradiction", "Contradiction: cache pod Running and Ready=True, restartCount=1 (01:14)", "context",
           r"Running and Ready=True", source="Splunk", check=True),
        _a("contra_replay", "contradiction", "Contradiction: replays succeed (REPLAYED) after Ready", "context",
           r"REPLAYED: Replay successful", source="SONAR", check=True),
        _a("ns_healthy", "contradiction",
           "Namespace hip-cloud-esb: 41/41 non-cache pods Ready, no network errors (rules out AKS/DNS blip)", "context",
           r"41/41 non-cache pods Ready", source="Splunk", ts_from="01:00:00", ts_to="01:10:00", check=True),
        _a("mem_before_restart", "context", "transco-cache memory ~96% just before the 00:20 restart", "context",
           r"mem_pct .* hip-fwk-transco-cache", source="Splunk", ts_from="00:10:00", ts_to="00:20:00"),
    ],
}
